name: A TO A:GH_PAGES
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: dong-jianbin/flow-pro-doc
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn build && cd docs/.vuepress/dist && echo 'flowpro.ddoogg.cn' > CNAME && cd -
        BUILD_DIR: docs/.vuepress/dist/